unstable_features = true
normalize_comments = true
# overflow_delimited_expr = false
reorder_impl_items = false
use_field_init_shorthand = true
# format_code_in_doc_comments = true
imports_layout = "HorizontalVertical"
imports_granularity = "Module"
group_imports = "StdExternalCrate"
# wrap_comments = true
